$(document).ready(function(){
     $("h3#one").click(function(q){
         q.preventDefault();
         $("#course1").toggle();
     });
 });
 $(document).ready(function(){
    $("h3#two").click(function(q){
        q.preventDefault();
        $("#course2").toggle();
    });
});
$(document).ready(function(){
    $("h3#three").click(function(q){
        q.preventDefault();
        $("#course3").toggle();
    });
});
$(document).ready(function(){
    $("h3#four").click(function(q){
        q.preventDefault();
        $("#course4").toggle();
    });
});
$(document).ready(function(){
    $("h3#five").click(function(q){
        q.preventDefault();
        $("#course5").toggle();
    });
});
$(document).ready(function(){
    $("h3#six").click(function(q){
        q.preventDefault();
        $("#course6").toggle();
    });
});
$(document).ready(function() {
    $("button#t1").click(function(q){
        q.preventDefault();
        $("#CS").toggle();
        $("#BA").hide();
        $("#BM").hide();
        $("#LS").hide();
        $("#acc").hide();
        $("#BF").hide();
        $("#COM").hide();
        $("#HIS").hide();
        $("#SE").hide();
        $("#DS").hide();
        $("#IT").hide();
        $("#CIV").hide();
        $("#ELE").hide();
        $("#MEC").hide();
        $("#VG").hide();
        $("#pd").hide();
    })
})
$(document).ready(function() {
    $("button#t2").click(function(q){
        q.preventDefault();
        $("#CS").hide();
        $("#BA").hide();
        $("#BM").hide();
        $("#LS").hide();
        $("#acc").hide();
        $("#BF").hide();
        $("#COM").hide();
        $("#HIS").hide();
        $("#SE").toggle();
        $("#DS").hide();
        $("#IT").hide();
        $("#CIV").hide();
        $("#ELE").hide();
        $("#MEC").hide();
        $("#VG").hide();
        $("#pd").hide();
    })
})
$(document).ready(function() {
    $("button#t3").click(function(q){
        q.preventDefault();
        $("#CS").hide();
        $("#BA").hide();
        $("#BM").hide();
        $("#LS").hide();
        $("#acc").hide();
        $("#BF").hide();
        $("#COM").hide();
        $("#HIS").hide();
        $("#SE").hide();
        $("#DS").toggle();
        $("#IT").hide();
        $("#CIV").hide();
        $("#ELE").hide();
        $("#MEC").hide();
        $("#VG").hide();
        $("#pd").hide();
    })
})
$(document).ready(function() {
    $("button#t4").click(function(q){
        q.preventDefault();
        $("#IT").toggle();
        $("#BA").hide();
        $("#BM").hide();
        $("#LS").hide();
        $("#acc").hide();
        $("#BF").hide();
        $("#COM").hide();
        $("#HIS").hide();
        $("#SE").hide();
        $("#DS").hide();
        $("#CS").hide();
        $("#CIV").hide();
        $("#ELE").hide();
        $("#MEC").hide();
        $("#VG").hide();
        $("#pd").hide();
    })
})

$(document).ready(function() {
    $("button#b3").click(function(q){
        q.preventDefault();
        $("#BA").toggle();
        $("#CS").hide();
        $("#BM").hide();
        $("#LS").hide();
        $("#acc").hide();
        $("#BF").hide();
        $("#COM").hide();
        $("#HIS").hide();
        $("#SE").hide();
        $("#DS").hide();
        $("#IT").hide();
        $("#CIV").hide();
        $("#ELE").hide();
        $("#MEC").hide();
        $("#VG").hide();
        $("#pd").hide();
    })
})
$(document).ready(function() {
    $("button#b1").click(function(q){
        q.preventDefault();
        $("#BM").toggle();
        $("#BA").hide();
        $("#CS").hide();
        $("#LS").hide();
        $("#acc").hide();
        $("#BF").hide();
        $("#COM").hide();
        $("#HIS").hide();
        $("#SE").hide();
        $("#DS").hide();
        $("#IT").hide();
        $("#CIV").hide();
        $("#ELE").hide();
        $("#MEC").hide();
        $("#VG").hide();
        $("#pd").hide();
    })
})

$(document).ready(function() {
    $("button#h1").click(function(q){
        q.preventDefault();
        $("#LS").toggle();
        $("#BA").hide();
        $("#BM").hide();
        $("#CS").hide();
        $("#acc").hide();
        $("#BF").hide();
        $("#COM").hide();
        $("#HIS").hide();
        $("#SE").hide();
        $("#DS").hide();
        $("#IT").hide();
        $("#CIV").hide();
        $("#ELE").hide();
        $("#MEC").hide();
        $("#VG").hide();
        $("#pd").hide();
    })
})
$(document).ready(function() {
    $("button#h2").click(function(q){
        q.preventDefault();
        $("#HIS").toggle();
        $("#BA").hide();
        $("#BM").hide();
        $("#LS").hide();
        $("#acc").hide();
        $("#BF").hide();
        $("#COM").hide();
        $("#CS").hide();
        $("#SE").hide();
        $("#DS").hide();
        $("#IT").hide();
        $("#CIV").hide();
        $("#ELE").hide();
        $("#MEC").hide();
        $("#VG").hide();
        $("#pd").hide();
    })
})

$(document).ready(function() {
    $("button#e1").click(function(q){
        q.preventDefault();
        $("#acc").toggle();
        $("#BA").hide();
        $("#BM").hide();
        $("#LS").hide();
        $("#CS").hide();
        $("#BF").hide();
        $("#COM").hide();
        $("#HIS").hide();
        $("#SE").hide();
        $("#DS").hide();
        $("#IT").hide();
        $("#CIV").hide();
        $("#ELE").hide();
        $("#MEC").hide();
        $("#VG").hide();
        $("#pd").hide();
    })
})
$(document).ready(function() {
    $("button#e2").click(function(q){
        q.preventDefault();
        $("#COM").toggle();
        $("#BA").hide();
        $("#BM").hide();
        $("#LS").hide();
        $("#acc").hide();
        $("#BF").hide();
        $("#CS").hide();
        $("#HIS").hide();
        $("#SE").hide();
        $("#DS").hide();
        $("#IT").hide();
        $("#CIV").hide();
        $("#ELE").hide();
        $("#MEC").hide();
        $("#VG").hide();
        $("#pd").hide();
    })
})
$(document).ready(function() {
    $("button#e3").click(function(q){
        q.preventDefault();
        $("#BF").toggle();
        $("#BA").hide();
        $("#BM").hide();
        $("#LS").hide();
        $("#acc").hide();
        $("#CS").hide();
        $("#COM").hide();
        $("#HIS").hide();
        $("#SE").hide();
        $("#DS").hide();
        $("#IT").hide();
        $("#CIV").hide();
        $("#ELE").hide();
        $("#MEC").hide();
        $("#VG").hide();
        $("#pd").hide();
    })
})

$(document).ready(function() {

    $("button#a1").click(function(q){
        q.preventDefault();
        $("#pd").toggle();
        $("#BA").hide();
        $("#BM").hide();
        $("#LS").hide();
        $("#acc").hide();
        $("#BF").hide();
        $("#COM").hide();
        $("#HIS").hide();
        $("#SE").hide();
        $("#DS").hide();
        $("#IT").hide();
        $("#CIV").hide();
        $("#ELE").hide();
        $("#MEC").hide();
        $("#VG").hide();
        $("#CS").hide();
    })
})
$(document).ready(function() {

    $("button#a2").click(function(q){
        q.preventDefault();
        $("#VG").toggle();
        $("#BA").hide();
        $("#BM").hide();
        $("#LS").hide();
        $("#acc").hide();
        $("#BF").hide();
        $("#COM").hide();
        $("#HIS").hide();
        $("#SE").hide();
        $("#DS").hide();
        $("#IT").hide();
        $("#CIV").hide();
        $("#ELE").hide();
        $("#MEC").hide();
        $("#CS").hide();
        $("#pd").hide();
    })
})

  $(document).ready(function(){

    $("button#en1").click(function(q){
        q.preventDefault();
        $("#MEC").toggle();
        $("#BA").hide();
        $("#BM").hide();
        $("#LS").hide();
        $("#acc").hide();
        $("#BF").hide();
        $("#COM").hide();
        $("#HIS").hide();
        $("#SE").hide();
        $("#DS").hide();
        $("#IT").hide();
        $("#CIV").hide();
        $("#ELE").hide();
        $("#CS").hide();
        $("#VG").hide();
        $("#pd").hide();
    })
})
$(document).ready(function(){

    $("button#en2").click(function(q){
        q.preventDefault();
        $("#ELE").toggle();
        $("#BA").hide();
        $("#BM").hide();
        $("#LS").hide();
        $("#acc").hide();
        $("#BF").hide();
        $("#COM").hide();
        $("#HIS").hide();
        $("#SE").hide();
        $("#DS").hide();
        $("#IT").hide();
        $("#CIV").hide();
        $("#CS").hide();
        $("#MEC").hide();
        $("#VG").hide();
        $("#pd").hide();
    })
})
$(document).ready(function(){

    $("button#en3").click(function(q){
        q.preventDefault();
        $("#CIV").toggle();
        $("#BA").hide();
        $("#BM").hide();
        $("#LS").hide();
        $("#acc").hide();
        $("#BF").hide();
        $("#COM").hide();
        $("#HIS").hide();
        $("#SE").hide();
        $("#DS").hide();
        $("#IT").hide();
        $("#CS").hide();
        $("#ELE").hide();
        $("#MEC").hide();
        $("#VG").hide();
        $("#pd").hide();
    })
})

$(document).ready(function() {
    $("#btn6").click(function(){
       alert("ThankYou for your interest, we'll get back at you shortly");
       window.location.href="../index.html";
    })
})

